### ISSUE TITLE
[Bug] CSV upload doesn't process

### ISSUE THREAD

**Issue by janhesters** [abramenal/cypress-file-upload#40] opened 2019-03-26 12:03 UTC
### Current behavior:

Here is the code that I use:

```js
  it.only('uploads a csv file, and logs the file', () => {
    cy.visit('/');
    cy.fixture('test.csv', 'ascii').then(fileContent => {
      cy.get('input#CSVReader').upload(
        {
          fileContent,
          fileName: 'test.csv',
          mimeType: 'text/comma-separated-values'
        },
        { subjectType: 'input' }
      );
    });
  });
```

Here is the error message:

```js
InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
```

### Desired behavior:

The file should get uploaded correctly and trigger [the `onFileUpload` method.](https://github.com/nzambello/react-csv-reader)

### Steps to reproduce: (app code and test code)

Here is the code for the component:

```js
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import CSVReader from 'react-csv-reader';
 
function App() {
  function handleFileUpload(f) {
    console.log(f);
  }

  function handleFileUpload(f) {
    console.log(f);
  }

  return (
    <CSVReader
      cssClass="csv-reader-input"
      label="Select CSV"
      onFileLoaded={handleFileUpload}
      onError={handleError}
      inputId="CSVReader"
      inputStyle={{color: 'red'}}
    />
  );
}
 
ReactDOM.render(<App />, document.getElementById('root'))
```

The code for the test is above.

Folder structure:

`src/App.js`, `cypress/fixtures/test.csv` and `cypress/integration/example_spec.js`.

### Versions

Cypress: 3.1.5
Mac: Mojave 10.14.3
Browser: 73.0.3683.86

**Comment by abramenal** [comment] 2019-03-26 12:11
Hi @janhesters 
Thanks for submitting the issue!

I was kinda expecting this issue to appear because some of the files are not being processed properly with base64 strings. (see https://github.com/abramenal/cypress-file-upload/blob/master/index.js#L6).
CSV is a good example of that.

Will extend the implementation to support it during this week.
Any help on coding that is welcome! 😈

**Comment by janhesters** [comment] 2019-03-26 12:15
@abramenal Thank you for the fast answer!

I'm new to Cypress and I unfortunately have no idea of `Blob` files. Let me know if I can help in any way, but I'm afraid I can't help out with the code.

**Comment by abramenal** [comment] 2019-03-31 15:04
@allcontributors[bot] add @janhesters for question

**Comment by corinnen** [comment] 2019-04-18 17:48
I installed this plugin yesterday and still getting same error as above with uploading a csv file.

**Comment by abramenal** [comment] 2019-04-18 19:50
@corinnen have you tried setting `encoding` to `'utf8'`?

**Comment by corinnen** [comment] 2019-04-19 01:39
@abramenal,

`        const fileName = 'statistics.csv';
          const mimeType = 'text/comma-separated-values';
          const encoding = 'utf8';

          cy.fixture(fileName, encoding).then(fileContent => {
      cy.get('[data-qa="upload"]').upload({ fileContent, fileName, mimeType, encoding }, { subjectType: 'input' });
     
      cy.wait(3000);
      cy.get('[data-qa="import-modal"]')
    });`

**Comment by abramenal** [comment] 2019-04-19 14:37
@corinnen if you can share your component implementation as well, we can try to figure out what is the issue – at the moment all examples stored in this repo work as expected (both react drag-n-drop implementation and plain HTML5 input)

**Comment by corinnen** [comment] 2019-04-22 16:25
@abramenal, yes, I am sure that it is not a bug (feel free to close the issue), I am new to coding/cypress and struggling to implement the plugin.

**Closed** 2019-04-23 07:28 UTC
Labels: bug
