### ISSUE TITLE
[Bug] Return type of Cypress.Blob changed from Promise to Blob in Cypress 5.0

### ISSUE THREAD

**Issue by caitcif** [abramenal/cypress-file-upload#217] opened 2020-08-25 22:57 UTC
### Current behavior:

base64StringToBlob() no longer returns a Promise. Update the use of base64StringToBlob() to expect a returned Blob.Learn more

### Versions

Cypress 5.0

**Comment by anas-qa** [comment] 2020-08-26 04:58
@caitcif duplicated with [#214](https://github.com/abramenal/cypress-file-upload/issues/214)

**Comment by josephzidell** [comment] 2020-08-26 19:20
Closing as duplicate of #214

**Closed by josephzidell** 2020-08-26 19:20 UTC
Labels: bug
