### ISSUE TITLE
Unable to upload .xlsx file using file upload plugin

### ISSUE THREAD

**Issue by SidharthLala1** [abramenal/cypress-file-upload#216] opened 2020-08-20 22:43 UTC
### I am using file upload plugin to uploag imgages , csv file which works like fine now when i am trying to upload .xlsx file it throwing an error.

![image](https://user-images.githubusercontent.com/33153967/90832634-d69b7080-e363-11ea-8167-4edabdf31086.png)

### Desired behavior:

While using the file upload plugin and using the correct Blob type and mime , i belive i should be able to upload the .xlsx file format.

### Steps to reproduce: (app code and test code)

cy.fixture('asin_xlsx.xlsx', 'binary')
			.then(Cypress.Blob.base64StringToBlob)
			.then(fileContent => {
				cy.get('input[type=file]').upload({
					fileContent,
					fileName: 'asin_xlsx.xlsx',
					mimeType:
						'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
					encoding: 'utf-8',
				})
			})
### Versions

Cypress version 5.0 , Windows 64 bit , Windows 10 Pro
https://www.loom.com/share/da6acb11bc70424a9346dca35338fc38

**Comment by craiga** [comment] 2020-08-24 14:08
Is this a duplicate of (or at least related to) #214 ?

**Comment by josephzidell** [comment] 2020-08-26 19:22
@SidharthLala1 Does this work in Cypress v4.12.1?

**Comment by josephzidell** [comment] 2020-08-27 15:59
Alternatively, please test against [`v4.1.0`](https://github.com/abramenal/cypress-file-upload/releases/tag/v4.1.0)

**Comment by saschwarz** [comment] 2020-08-27 20:07
My pre-5.0 code for this uses `Cypress.Blob.binaryStringToBlob` and works:

```
      cy.fixture('simple_2017.xlsx', 'binary')
        .then(Cypress.Blob.binaryStringToBlob)
        .then((fileContent) => {
          cy.get('input[data-testid=pnl-input]').attachFile({
            fileContent,
            fileName: 'simple_2017.xlsx',
            mimeType:
              'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            encoding: 'utf8',
          })
        })
```

I don't think .xlsx files are base64 encoded

**Comment by ifilatov** [comment] 2021-01-14 01:05
@saschwarz does the snippet you shared work for you on current versions?
I have cypress-file-upload 4.1.1 and cypress 6.2.1 and sadly it does not work for me (no errors thrown on Cypress side, but my app UI thrown an error that was not able to parse xlsx and find excelSheet)

**Comment by abramenal** [comment] 2021-11-14 16:58
Don't think this is relevant anymore. Feel free to reopen if you still experience this.

**Closed by abramenal** 2021-11-14 16:58 UTC
Labels: bug, question
